### ISSUE TITLE
Secured services not sending token when reconnecting and submitting attachments

### ISSUE THREAD

**Issue by driskull** [Esri/offline-editor-js#286]
I was able to reproduce this using a hosted feature service that is not shared publicly. When going back online, it submits and sends a token for the feature but does not send a token for the attachment so it fails.

It seems like when going back online and submitting attachments, it needs to send a token along if necessary.

Esri/geoform-template-js#106

**Comment by andygup** [comment]
@driskull Thanks. It looks like attachmentsStore.js needs to explicitly manage the attachments token. My guess is the current architecture simply doesn't understand how to handle it.

**Comment by andygup** [comment]
@driskull Like we discussed, I've gone ahead and moved this to v2.6 since it is dependent on v2.5.

This needs some additional investigation into the following use cases:
* Support for token-based authentication, only.
* Gracefully handling any failure on an HTTPS connection. E.g. expired token. Note: v2.5 keeps edits and basic information on edits that fail to sync with server. It also emits a specific event when there is a failure to sync any edits. This may need some additional enhancement to store error information.
* Need to respect and store information related to [FeatureLayer.credential](https://developers.arcgis.com/javascript/jsapi/featurelayer-amd.html#credential).

References: 
* http://doc.arcgis.com/en/arcgis-online/administer/configure-security.html
* https://developers.arcgis.com/javascript/jshelp/ags_secureservices.html
