### ISSUE TITLE
Multiple Feature Layers in Offline Mode

### ISSUE THREAD

**Issue by Ricardh522** [Esri/offline-editor-js#371]
I am building a widget that utilizes the advanced tiles and the edits library.  My question is in regards to the edit library.  In order to load and manage multiple feature layers with the offline Feature Manager (oFM), should I instantiate one oFM for each feature layer or should I re-code the methods in the library to handle an array of feature layers?  

The problem I am having is that when extending each layer in an array or layers, the race conditions prevent all but the last put to commit.  When setting breakpoints at the offlineManager.extendFeatureLayer method in my application each json dataStore loads into indexedDB.

I've been putting each feature layer in a separate Data Store with the key being the layer name.  Should I instead put all of the layers into one Data Store? 

My code is constantly changing so it would not do any good for me to put in a sample at this point.

**Comment by andygup** [comment]
Can you clarify that you are asking about full offline capabilities that include restarting the browser while offline? It looks like it from the coding patterns suggested in your question but I'd like to be 100% sure. Otherwise, these patterns are not required for intermittent offline use cases.

>>should I instantiate one oFM for each feature layer or should I re-code the methods in the library to handle an array of feature layers?

You should instantiate a single instance of the offlineFeaturesManager library and then extend the array of feature layers as demonstrated here in the [draw-pointlinepoly-offline.html](https://github.com/Esri/offline-editor-js/blob/master/samples/draw-pointlinepoly-offline.html#L187) sample. 

>>Should I instead put all of the layers into one Data Store?

Yes, only one Data Store is allowed and there are two options for managing it. Note, if you attempt to use two Data Stores then the last one will overwrite the previous one (LIFO pattern). 

Approach 1 involves you manually creating the Data Store for greater control over what goes into the Data Store Object and then inserting that Object into the offlineFeatureManager's constructor.

Approach 2, you can let the library manage it automatically upon an ADD, UPDATE or DELETE. This is accomplished by not inserting a manual Data Store Object into offlineFeatureManager constructor and instead setting [`offlineFeaturesManager.ENABLE_FEATURECOLLECTION = true`](https://github.com/Esri/offline-editor-js/blob/master/doc/offlinefeaturesmanager.md).

More details on these two approaches can be here in the [How to use the edit library](https://github.com/Esri/offline-editor-js/blob/master/doc/howtouseeditlibrary.md) and usage patterns are mentioned specifically in `Step 4`. 

My TO-DOs: document the need for a single Data Store object and clarify the LIFO pattern, clarify the two approaches in the appcache-features.html sample.

**Comment by Ricardh522** [comment]
Hi Andy,  Thank you so much for your reply and for pointing our the point-line-poly sample.  I tend to overlook things sometimes.  The use case for my application is for complete and semi-offline viewing of a dynamic map service.  No editing is required at this point.  If they like the project and want to proceed with editing then I will get back to work.  

For the time being I've put together what I believe to be a solid solution that uses your offline tiles library and concepts from your editing features library to handle the offline-online transitions.  There are two types of offline in my use case.  Not able to connect to the internet at all, and not being able to connect to the local gis server but able to pull tiles from AGOL.  

I read through the indexedDB spec and put together some functions for putting, reading, and clearing the json from the dataStore.

https://github.com/Ricardh522/offline-app-code

If you could grade my work it would be a great benefit for me and my gis team.  No one else really knows this stuff and they are relying on me to deliver this solution.

Thanks,

Richard

**Comment by andygup** [comment]
Glad to help.

>>I read through the indexedDB spec and put together some functions for putting, reading, and clearing the json from the dataStore.

Where you aware that the library has existing methods for doing just that? I recommend using the built-in, existing methods for working with this library's databases. 

Here's the shortcut link to all the [API docs](http://esri.github.io/offline-editor-js/demo/api-doc.html ) that has all the methods, properties and events. The API docs are pretty much up to date.

There are two ways to get the dataStore. You can get it from the instance of Offline Features Manager or from the feature layer, itself:
* offlineFeaturesManager.getFeatureLayerJSONDataStore( callback )
* featureLayer.getFeatureLayerJSONDataStore(callback) 

There is also a method for setting the dataStore, and it can also be used to clear the dataStore:
* featureLayer.setFeatureLayerJSONDataStore( jsonObject, callback)
 
>>If you could grade my work it would be a great benefit for me and my gis team

If you have a block of code or a GIST and specific questions about it, I'm happy to provide pointers as related to our JS API or this library.

**Comment by andygup** [comment]
@Ricardh522 any luck?

**Comment by Ricardh522** [comment]
I've been putting my time recently towards optimizing the offline capability through the app cache.  I am adapting the code into the EsriSlurpBuild to get some optimization through dojo build.  I'm basically learning dojo build by studying the EsriSlurp Template.

**Comment by andygup** [comment]
I'm going to close this for now. If the same issue comes back up please feel free to reopen.
