### ISSUE TITLE
O.esri.Tiles.OfflineTileEnablerLayer fails without dbConfig 

### ISSUE THREAD

**Issue by pstevlingson** [Esri/offline-editor-js#381]
O.esri.Tiles.OfflineTileEnablerLayer fails when not using dbConfig.

ie...
var tileLayer = new O.esri.Tiles.OfflineTileEnablerLayer("http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer",function(evt){
                // console.log("Tile Layer initialized for offline. App state is: " + Offline.state);
            },_isOnline)

I believe that line 34 in offline-tiles-advanced-src.js should not have the quotes around the undefined keyword because its using the strict comparison.  "===".   Other parts of the code do not use the surrounding quotes.

I'm testing in the latest version of chrome on windows7.

if( dbConfig === "undefined" || dbConfig === null){

**Comment by andygup** [comment]
@pstevlingson This was a known bug that's been fixed in [v2.11.0](https://github.com/Esri/offline-editor-js/blob/master/dist/offline-tiles-advanced-src.js#L34). It looks like I forgot to document the fix, but it's there.

Are you using the latest version of offline-tiles-advanced-src.js? The version number should be on [line 1](https://github.com/Esri/offline-editor-js/blob/master/dist/offline-tiles-advanced-src.js#L1).

**Comment by pstevlingson** [comment]
I have v2.10.0.    This was my first GIT pull.   I'll look for a newer patch next time.   The offline library will be pretty handy.   

Thanks
