### ISSUE TITLE
Editing via table

### ISSUE THREAD

**Issue by DShokes** [Esri/offline-editor-js#408]
Are there any plans to enable offline attribute editing via table? This would be much more efficient than using the attribute inspector in many use cases.

**Comment by andygup** [comment]
@DShokes Can you elaborate a bit more on this? 

If someone where to build a custom, table-based editor, they could set it up to work with the `offlineFeaturesManager` library. The library can work with valid `applyEdits()` requests.

**Comment by DShokes** [comment]
I saw online table editing in your other repo called [feature-service-editor-js](http://github.com/Esri/feature-service-editor-js). It was deprecated and replaced by [esri/dijit/featureTable](http://developers.arcgis.com/javascript/jsapi/featuretable-amd.html). However, the featureTable widget does not allow attributes to be edited within cells. In fact, the readOnly parameter was taken out of the featureTable documentation making it unclear when cell editing be built into the Javascript API.

How difficult it would be to adapt your offline library to other esri widgets like the [Crowdsource-Manager data-viewer](http://github.com/Esri/crowdsource-manager/tree/master/js/widgets/data-viewer) or the [Batch Attribute Editor](http://github.com/Esri/solutions-webappbuilder-widgets/tree/master/BatchAttributeEditor)?

It would be great to see a version of your offline [Feature Editing Sample](http://esri.github.io/offline-editor-js/samples/draw-pointlinepoly-offline.html) with an editable table tied to the map!

**Comment by andygup** [comment]
Gotcha! Thanks for the additional info. I can speak to my own experience with building a full functionality, table-based editor in that it was challenging to keep it up to date with a wide variety of use cases while attempting to stay cross-browser compatible. If you tack on mobile plus desktop browsers it gets even trickier. 

>> In fact, the readOnly parameter was taken out of the featureTable documentation making it unclear when cell editing be built into the Javascript API.

If that functionality does get built, my hunch is it would be in JS API v4.x. What would carry the most weight is if you submit an enhancement request thru tech support and back it up with some solid use cases.

>> How difficult would it be to adapt your offline library to other esri widgets like the Crowdsource-Manager data-viewer or the Batch Attribute Editor?

Not sure since I'm not familiar with the source of those projects. My suggestion would be to give it a try: bolt in the widget, assign it an offline-enabled feature layer and then force `offlineFeaturesManager` library offline. 

Since those widgets have publicly available source code it should be fairly straightforward to troubleshoot any errors. Most of the offline issues I've seen with widgets have to do with the life-cycle of promises and during application restarts. 

>> It would be great to see a version of your offline Feature Editing Sample with an editable table tied to the map!

I would love to do it if I had the time to build and maintain it, however per my first comment I don't see it happening any time soon.

**Comment by andygup** [comment]
@DShokes quick update on the editing of cells in FeatureTable -> possible by 3.15, definitely planned by JS API 4.0 final.

**Comment by andygup** [comment]
@DShokes I'm going to close this issue for now. If you have specific implementation questions feel free to reopen.

**Comment by DShokes** [comment]
Great. Thanks for the updates!
