### ISSUE TITLE
Offline extend making webmap layer show incorrectly

### ISSUE THREAD

**Issue by driskull** [Esri/offline-editor-js#417]

**Comment by driskull** [comment]
Hey @andygup here's the test app: https://github.com/driskull/offline-display

**Comment by driskull** [comment]
http://driskull.github.io/offline-display/demo.html

**Comment by andygup** [comment]
Verified. For now there are two work-arounds: roll your library back to around v2.9 or use tiled base maps with stand-alone feature layers. 

At the moment, a timeframe for a fix is unknown. It will take some time to investigate.

**Comment by andygup** [comment]
Thanks to the additional help from @driskull I'll close this out.

**Recap:** This issue is related to Web Maps that have feature layers. It will cause feature layer graphics to disappear, or only a subset of the graphics will appear, or they may flash temporarily and reappear/disappear.

**Summary:** this has to do with how the `featureLayer.objectIdField` gets set.  `offlineFeaturesManager` library defaults to setting that property to `objectid` in all lower case. You may have to change this to `OBJECTID` or even something completely different if you have a custom created feature layer.

Example:

```javascript
offlineFeaturesManager = new O.esri.Edit.OfflineFeaturesManager();

// IMPORTANT!!!
// This tells the database which graphic.attribute property to use as a unique identifier
// You can look this information up in your feature service directory under the "Fields" category.
// Example: http://services1.arcgis.com/M8KJPUwAXP8jhtnM/arcgis/rest/services/Denver_Bus_Stops/FeatureServer/0
offlineFeaturesManager.DB_UID = "OBJECTID";
```
