### ISSUE TITLE
How to create tpk?

### ISSUE THREAD

**Issue by rfanning78** [Esri/offline-editor-js#435]
I can successfully use the library with Beirut.zip. I'm trying to create a tile package of the world basemap using ArcMap. Unfortunately the resulting .tpk is much smaller and the map doesn't appear. Can you explain how you created Beirut? Thanks!

**Comment by andygup** [comment]
Hi, just an FYI, in the future it's best to use a short and easily searchable title and then post the content as a comment. It looks like you accidentally wrote your entire comment into the title.

As for the Beirut.tpk file, are you trying to convert the entire world basemap into a tpk? As a best practice, this library works best with TPKs that are no larger than 75MB - 100MB that cover small geographic areas. This is simply due to on-device browser limitations. If you need a TPK larger than that you'll need to consider switching over to our native Runtime SDKs.

If you are planning on using the TPK along with a tiled map service then the LODs in the map service have to exactly match those of the TPK: [How To Use](https://github.com/Esri/offline-editor-js/blob/master/doc/howtousetpklibrary.md) doc.

**Comment by andygup** [comment]
@rfanning78 I went ahead and fixed the title and then moved your question into a comment. If it looks different that's what happened. It was something I was easily able to tweak.

**Comment by andygup** [comment]
@rfanning78 are you good on this? Let me know and/or close this one out.

**Comment by rfanning78** [comment]
Unfortunately I still haven't been successful creating a tile package from ArcMap that works with this library.  I'm sure I'm doing something wrong.  It doesn't matter if I'm doing a small map or a large one, I'm not getting tiles to appear.  Thanks.

**Comment by andygup** [comment]
Are you seeing any errors in the browser console? And, if you are able to attach a tpk here I can take a look at it.

**Comment by rfanning78** [comment]
I created a tpk for a small area of the world.  I'm not getting any errors in the browser, however what appears in my application is a rectangle with 'NO TILE'.  I'm working in an offline environment so it's difficult for me to attach the tpk I created from ArcMap.

**Comment by andygup** [comment]
@rfanning78 I've seen situations were the TPK is loaded and you simply need to zoom down to the correct level. 

1) Can you copy and paste the full console log representing loading the app, loading the TPK and then zooming down as far as it will zoom in?

2) Let me know the answers to these questions:
* What browser and version are you using?
* How large in MBs is your TPK?
* What spatial reference is the TPK?
* How many levels are in the TPK?

3) Check the contents of the library's database. In Chrome it's under the Resources tab. Copy and paste a screenshot of the IndexedDB console log for the table `offline_tile_store`. It should look something like this:

![image](https://cloud.githubusercontent.com/assets/510440/12268170/de510298-b908-11e5-85e4-61ca96781227.png)

**Comment by rfanning78** [comment]
Browser: FireFox 42.0
Size: 5.24 MB
Spatial Reference: 102100 (I think)
I can't copy and paste from my development system, but attached are snippets of my messages.
[ConsoleOutput.txt](https://github.com/Esri/offline-editor-js/files/97382/ConsoleOutput.txt)

**Comment by rfanning78** [comment]
I didn't mean to close.

**Comment by andygup** [comment]
@rfanning78 Got it. I don't see any errors and there are no images being stored in the database after loading and zooming is complete. That does help narrow things down a notch and potentially means the issue has to do with how the TPK is being created. 

Here are some more questions:

* Can you provide any additional details about what are you using for a basemap? I'm asking since you weren't sure of the spatial reference.
* Have you verified that you have a valid tpk by trying to load it in Desktop after you create it?
* Do you have access to a local ArcGIS Server, and if so have you tried using the  [exportTiles](http://resources.arcgis.com/en/help/arcgis-rest-api/#/Export_Tiles/02r300000262000000/) approach?

**Comment by rfanning78** [comment]
After a lot of trial and error I'm finally able to create basemaps in ArcMap.  Thanks for all your help.
