### ISSUE TITLE
OfflineEditAdvanced - after multiple offline restarts, UID begins at -1 again for Adds

### ISSUE THREAD

**Issue by robkspeer** [Esri/offline-editor-js#448]
Hi Andy, I noticed that after an offline restart, and recreating features from ```offlineFeatureManager.getFeatureLayerJSONDataStore(success,dataStore){...}```, the dataStore correctly populates the OIDs of any features created in the first offline-loaded session with their respective temporary negative numbers.

But on subsequent offline restarts, when creating another new feature, the features created in the new session will start over at -1, which then performs an Update on the previously assigned OID-1, instead of an Add of a new feature with OID -2.

Perhaps I'm just missing something -- Is there a way to point the offline Feature Layer to the existing OIDs of recreated features, so that the OfflineEditAdvanced correctly picks up where the previous session left off?

Thanks,
-rob.

**Comment by andygup** [comment]
Interesting we didn't find that sooner. Looks like a possible bug related to [layer._nextTempId](https://github.com/Esri/offline-editor-js/blob/master/lib/edit/OfflineEditAdvanced.js#L1153).

Here's one possible approach to fixing it unless you have other thoughts on it. I haven't thought thru all the logic flow, so this may not be complete: 
- Create a new database query that looks for tempIds and returns the lowest value or null if no tempIds exist. Conceptually it would loop all edits in a way similar to [EditStore.getAllEdits()](https://github.com/Esri/offline-editor-js/blob/master/lib/edit/editsStore.js#L506).
- Before creating a new tempId, query the database. If that query returns null then start at -1, otherwise increment starting with the value returned by the database.

Lemme know if this is something you want to take a crack at? If not, I'm at DevSummit next week and can check into fixing this after that wraps up.

**Comment by robkspeer** [comment]
I figured you might be busy getting ready for next week.  I am sitting the Dev Summit out this year, so I will try to take a look in the mean time and report back anything I come up with.  Thanks Andy.

**Comment by robkspeer** [comment]
I think I've got this issue resolved, however, I had some problems with the Grunt task and Uglify's ```preserveComments: 'some' ``` option where it was leaving all comments in the built dist files.

I commented out ```Uglify.options.preserveComments``` for this build, but this also seems to have taken out your Esri header in the -min.js files?  We can look at the Gruntfile.js or where that's going wrong, or I can just paste in the header.

When you have time, please review my [PR 449](https://github.com/Esri/offline-editor-js/pull/449) and let me know how you'd like me to proceed.

In the mean time, I'll be using v3.0.6 and I'll revise if we come across any issues.

Thanks!

**Comment by andygup** [comment]
@robkspeer where did we leave off, is there anything in my court that you are waiting on? Or have you bolted in the suggested mods and this is good to merge?

**Comment by robkspeer** [comment]
I'm out of town at the moment, but if you are good with just getting rid of the "else" that was in question, i'll wrap this up Friday with a new commit.

**Comment by andygup** [comment]
Sounds good, there's actually two final changes to bolt in, then let'er rip:
- remove `else`. The default value of `-1` is handled by default in your `this.getNextLowestTempId()` method.
- modify `preserveComments: /^!/` in gruntfile.js and then rerun `grunt build`. That way any future builds will automatically remove comments correctly.

**Comment by robkspeer** [comment]
I've just opened #451, and depending on your thoughts on it, I'll look at that for the v3.0.6 PR as well.
