### ISSUE TITLE
proxyPath not respected in OfflineEditAdvanced

### ISSUE THREAD

**Issue by hoesli** [Esri/offline-editor-js#461]
In OfflineEditAdvanced only credentials are used for requests. Setting the proxyPath has no effect.

Line 2058 should be something like that:
```
var url = this.proxyPath ? this.proxyPath + "?" + layer.url : layer.url;

var req = new XMLHttpRequest();
req.open("POST", url + "/applyEdits", true);
```

**Comment by andygup** [comment]
Sure enough, good catch. Looks like all references to proxyPath got accidentally removed at some point. It was easy to overlook since almost everything we use is CORS-enabled.

I'll take a look thru the entire OfflineEditAdvanced library to make sure no other references are missing then push up a fix.

**Comment by andygup** [comment]
Related note - same problem in OfflineEditBasic.
