### ISSUE TITLE
Features created offline lack OBJECTID attribute after returning online and syncing.

### ISSUE THREAD

**Issue by bjvanmet** [Esri/offline-editor-js#491]
Hi Andy,

I can't believe I'm just now finding this bug!
Here's the report...

#### Expected behavior

- Which offline library are you using (e.g. OfflineEditBasic.js, OfflineTilesAdvanced, etc)? 
-- OfflineEditAdvanced
- What's the offline library version number?
-- v3.0.3
- Describe what you expected or wanted to happen.
-- Create a feature while offline. Return online and sync. Feature should have OBJECTID go from a negative number (for offline db) to a positive number assigned by server, which does come back from the callback function.
- What you are trying to achieve?
-- Creating an application that allows users to use tablets to enter data in the field where they may expect to lose data connection (WiFi or 4G). 

#### Actual behavior

- Describe what occurs in your code.
-- Features created offline and synced lack an OBJECTID attribute. Without this, users cannot delete objects created offline without first refreshing the web page to reload the app.
- Specifically, what seems to work differently than you intended?
-- The above is plenty specific :)
- Provide any error messages you see in the console.
-- No Error messages.

#### Steps to reproduce the behavior
* This works in the offline edit sandbox right here in github: http://esri.github.io/offline-editor-js/samples/simple-edit.html.

* Open a browser console (I'm using Chrome). Enter this command:
map.getLayer("lineFeatureLayer").graphics;
Note that in the result, the last feature listed in the graphics array has an OBJECTID attribute.

* Go through the workflow of the page (go offline, draw a polyline, go online).
Enter the same command as above into the browser console. There will be a new object added to the graphics array. Notice there is no object id until you reload the page. For what it is worth, refreshing the layer does not get this OBJECTID attribute populated.

Thanks for looking into it,
-Bryan

**Comment by andygup** [comment]
@bjvanmet Just confirming you are running v3.0.3? 

Good catch, btw. I am able repro this in v3.6.0 which is the latest and greatest. 

Looks like a bug in `OfflineEditBasic` and `OfflineEditAdvanced` where `var graphic = new Graphic(adds[0].geometry,null,adds[0].attributes);`  The problem is that `adds[0].attributes` doesn't inject the `addsResult.objectId`. 

I'll bolt in a fix, and you'll need to upgrade and restest when I'm done.

![image](https://cloud.githubusercontent.com/assets/510440/19870735/81a19ce6-9f77-11e6-8946-ee4b81a08255.png)
