### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by RawenC** [Esri/offline-editor-js#507]
Hello, i am trying show in map .tpk file (Beirut.zip), but everytime when i changed projection (scale/center) i got some errors. 

![obrazek](https://user-images.githubusercontent.com/48750601/54669844-a0b0e780-4af2-11e9-8bb1-980b09b82b5a.png)

Its looks like some image squares are not loaded, but map looks correct.

![obrazek](https://user-images.githubusercontent.com/48750601/54669486-c8ec1680-4af1-11e9-9042-abea359fde6c.png)

So my question is, is it normal? or can i fix it somehow? I am using Chrome 73.0.3683.75, but have this errors on firefox too..

**Comment by andygup** [comment]
@RawenC the errors are annoying but shouldn't affect functionality. If I remember correctly, they are just a side effect of the async nature of the `TiledMapServiceLayer.getTileUrl()` method.

**Comment by RawenC** [comment]
Is any way how stop showing this errors with some try/catch?

**Comment by andygup** [comment]
You are welcome to give it a try by hosting the source code locally. The error is happening internally in the ArcGIS API for JavaScript `FeatureLayer.getTileUrl()` method. You could try experimenting by using a blank image url instead of `void`, I haven't looked at the code in a while so I'm not sure what the side-effects might be.

**Comment by RawenC** [comment]
Thanks for the tip, I'll try.

**Comment by andygup** [comment]
Closing due to no further activity.
